### ISSUE TITLE
Reps

### ISSUE THREAD

**Issue by Lightt10** [MrPowerGamerBR/owo#355]
**Qual é o problema?**
O comando de reps não esta funcionando imagem abaixo:
Descrição maravilhosa sobre qual é o problema

**Como reproduzir o problema?**

1. Procure suas reps ou a de outro usuário
![Screenshot_20220316-173604](https://user-images.githubusercontent.com/99568849/158687006-29da454a-a990-4c02-800d-4f49c995bef2.png)

**Comment by MrPowerGamerBR** [comment]
Significa que o usuário não tem reputações, mas a mensagem é realmente um problema

**Comment by MrPowerGamerBR** [comment]
Duplicata: https://github.com/LorittaBot/DreamLand/issues/260
