### ISSUE TITLE
Bug no comando de slash da Loritta.

### ISSUE THREAD

**Issue by SnumpusGx** [MrPowerGamerBR/owo#356]
**Qual é o problema?**

O comando de Undertale textbox custom não funciona.

**Como reproduzir o problema?**

1. uso /undertale textbox custom
2. Coloco um texto na parte "text"
3. Escolho o "attachment" (imagem) da minha galeria para o comando "image_file"
4. Me deparo com o erro "This interaction failed".

**Considerações Finais**

http://http.cat/404

**Comment by MrPowerGamerBR** [comment]
![image](https://user-images.githubusercontent.com/9496359/159097297-24918840-1641-480a-972d-e4845e8f55a0.png)

Você pode enviar qual imagem você tentou enviar aqui?

**Comment by SnumpusGx** [comment]
> ![image](https://user-images.githubusercontent.com/9496359/159097297-24918840-1641-480a-972d-e4845e8f55a0.png)
> 
> Você pode enviar qual imagem você tentou enviar aqui?

Eu tentei mandar qlqr imagem da minha galeria, fiz com 2 ou 3 imagens que tavam na minha galeria e só retornava com "Essa interação falhou", mas acho que isso ainda é bug no discord, pois eu estava tentando fazer isso no cliente de mobile (Android)

**Comment by MrPowerGamerBR** [comment]
> "Essa interação falhou", mas acho que isso ainda é bug no discord, pois eu estava tentando fazer isso no cliente de mobile (Android)

Atualize o Discord, eles mudaram uma coisa no backend deles que quebrou clients antigos.

**Comment by SnumpusGx** [comment]
> > "Essa interação falhou", mas acho que isso ainda é bug no discord, pois eu estava tentando fazer isso no cliente de mobile (Android)
> 
> Atualize o Discord, eles mudaram uma coisa no backend deles que quebrou clients antigos.

Ok
