### ISSUE TITLE
Funcionalidade Raspadinha

### ISSUE THREAD

**Issue by FarBST** [MrPowerGamerBR/owo#357]
Caso o usuário compre mais de uma raspadinha, ele poderá raspar todas de forma mais rápida, assim podendo ver todos os possíveis ganhos. 

Exp.: você comprou 5 raspadinhas e ganhou um total de X sonhos...

A própria loritta já rasparia e diria todos os resultados.

**Comment by 0spura** [comment]
Então não vai ser uma raspadinha se você não raspa. Vai perder o sentido do comando.

**Comment by MrPowerGamerBR** [comment]
Como o @luissfx disse: O objetivo da raspadinha é você mesmo raspar, essa que é a graça, se mudasse não ia ser tão legal o comando.
