### ISSUE TITLE
rbuser bug

### ISSUE THREAD

**Issue by TobizinOtirra** [MrPowerGamerBR/owo#360]
**Qual é o problema?**

com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 12 path $

***Descrição maravilhosa sobre qual é o problema***

ao usar o +rbuser em algum player do roblox acontece este erro

**Como reproduzir o problema?**

1. pegue um nick de alguém no roblox
2. use +rbuser *nick do jogador*
3. basta esperar a lori responder
4. não sei se serve link da imagem que coloquei em chat pv meu, mas está aqui https://media.discordapp.net/attachments/832812483034742815/957828790514491432/IMG_20220327_232806.jpg

**Comment by MrPowerGamerBR** [comment]
Eu migrei o `+rbuser` para Slash Commands e arrumei o bug! `/roblox user`
