### ISSUE TITLE
Loritta morre ao usar um comando

### ISSUE THREAD

**Issue by Vordlex** [MrPowerGamerBR/owo#366]
**Qual é o problema?**

Ao usar o comando +rank, na loritta Cluster 16 (297153970613387264), o bot simplesmente fica inutilizável por alguns segundos

**Como reproduzir o problema?**

1. Vá em algum servidor que tenha a loritta
2. escreva o comando +rank
3. o bot não responderá por alguns instantes.
![image](https://user-images.githubusercontent.com/43836184/163202423-d83df9f4-3b2d-4c83-8c53-7d9e818f8748.png)

**Comment by MrPowerGamerBR** [comment]
Como ali dá para ver que estava dando erro 503 Internal Server Error, provavelmente o problema era que o Discord estava com problemas na API dele.
