### ISSUE TITLE
Comandos em Slash de minecraft estão bugados

### ISSUE THREAD

**Issue by mayacel** [MrPowerGamerBR/owo#376]
**Qual é o problema?**

Comandos em Slash de minecraft esta bugados

**Como reproduzir o problema?**

1. O comando do +mcbody e outros em slash esta bugado, ao executar aparece uma mensagem de erro da loritta e depois uma de java
2. De /minecraft player body e outros, o avatar e head também estão bugados
3. A mensagem que a loritta envia mostra o bug
4. ![Screenshot_20220423-213926_Discord.jpg](https://user-images.githubusercontent.com/103088929/164950992-9821d74c-b941-4fe7-bfae-d5f21c8c4946.jpg)

**Comment by MrPowerGamerBR** [comment]
Isso eu já tinha arrumado faz alguns meses mas não tinha fechado a issue, whoops
