### ISSUE TITLE
+correios

### ISSUE THREAD

**Issue by Pedrin268** [MrPowerGamerBR/owo#380]
**Qual é o problema?**

Quando você usa +correios e o pacote não esta no sistema ele da um erro de locale !!{commands.command.packageinfo.invalid}!!

**Como reproduzir o problema?**

1. Use +correios e coloque qualquer código de rastreamento que não esteja no sistema deles
![image](https://user-images.githubusercontent.com/39220125/167452057-108a6b35-b7cd-420d-80b7-d690693bd4cc.png)

**Considerações Finais**

Gatin
![gato-fofo](https://user-images.githubusercontent.com/39220125/167452186-07c77432-c8ff-45e2-aaf9-0a878ac23a8c.jpg)

**Comment by MrPowerGamerBR** [comment]
O `+correios` foi substituido pelo `/package info`, e no `/package info` esse bug foi corrigido.
