### ISSUE TITLE
Bug Lorrita <3

### ISSUE THREAD

**Issue by hym4r0** [MrPowerGamerBR/owo#383]
**Qual é o problema?**
Quando executo o comando +mcstatus ela indica o erro: Alguma coisa deu extremamente errada ao executar este comando... :lori_rage~1: Desculpe pela inconveniência. :lori_sob: java.net.UnknownHostException: status.mojang.com
**Como reproduzir o problema?**

1. Primeiro entra em algum canal de comando.
2. depois digite +mcstatus
3. Pronto!

**Considerações Finais**

Não tem foto mas... miau! - meu dc hymaro#0009

**Comment by MrPowerGamerBR** [comment]
A Mojang removeu a página de status deles, como também ela nem estava mais sendo atualizada faz uns anos

Então eu acho que o jeito é remover o comando da Loritta

**Comment by hym4r0** [comment]
Entendi, obrigado powerhumilde

**Comment by MrPowerGamerBR** [comment]
O comando foi removido já que né, o website de status não existia mais (rip)
