### ISSUE TITLE
Bot mostra as Permissões que você possui no servidor em js

### ISSUE THREAD

**Issue by SrTrindade** [MrPowerGamerBR/owo#384]
**Qual é o problema?**

Bot mostra as Permissões que você possui no servidor em js

**Como reproduzir o problema?**

Utilizando o comando +perfil, na segunda pagina da embed, as permissões que você possui no servidor que foi enviado o comando,

{discord.permissions.messageExtSticker}!! { Adicionar Stickers )
{discord.permissions.manageThreads}!! ( Gerenciar Tópicos ) 
{discord.permissions.usePublicThreads}!! ( Usar Tópicos Públicos )
{discord.permissions.usePrivateThreads}!! ( Usar Tópicos Privados )
{discord.permissions.requestToSpeak}!! ( Utilizar a voz de áudio em mensagens de texto )

Essas estão aparecendo em Java script, bom receio que seja um bug, se não for, releva

**Considerações Finais**

Anexo:

![image](https://user-images.githubusercontent.com/40744299/169438692-7961ba2a-9f61-46fb-89c7-5312fe43929b.png)

**Comment by MrPowerGamerBR** [comment]
"em js" JavaScript tem nada a ver com o problema.

Novas permissões foram adicionadas no Discord, eu não coloquei os textos delas nos arquivos de tradução dela. Esse bug foi "corrigido" no `/user info` (em aspas pois na realidade o `/user info` foi feito do zero) não tem este problema.
