### ISSUE TITLE
Servidor sa-mp

### ISSUE THREAD

**Issue by EchoicYeti** [MrPowerGamerBR/owo#390]
**Qual é a sua sugestão?**

- Ter um servidor tipo sparkly, só que GTA sa-mp

Sugestão incrível maravilhosa chocante que vai arrebentar o mundo...

**Porque a sua sugestão deve ser adicionada na Loritta?**

- Pq assim seria mais "fácil" ganhar sonhos, pq "muita" gente não joga Minecraft ou não gosta sla... A comunidade SA-MP/RP está crescendo muito acho que séria bom

**Comment by MrPowerGamerBR** [comment]
Eu não jogo GTA:SA MP, então não faz sentido eu abrir um servidor de um jogo que eu nem jogo.
