### ISSUE TITLE
Pequeno problema não formatação do info usuário 

### ISSUE THREAD

**Issue by Pekeanugab** [MrPowerGamerBR/owo#393]
**Formatação info usuário**

O problema se deve a fazer comando de  "info" que possivelmente pode ser acessado no perfil em [Apps] em que a formatação dos emojis está com esses pequeno problema que pode não ser considerado um probleminha apenas um erro.

**Como reproduzir o problema?**

Vamos lá primeiramente deve-se ir em [perfil] > [apps] > [View info] bem fácil não é?

[Imagens]

https://media.discordapp.net/attachments/979706784770031639/984955326673588274/Screenshot_20220610-183733_Discord.jpg
https://media.discordapp.net/attachments/979706784770031639/984955327076237412/Screenshot_20220610-183810_Discord.jpg

Espero ter ajudado!

Ps: Desculpe se tiver algum erro de português é porque estou com fome e um pouco de sono.

**Comment by 0spura** [comment]
Verifica se a Loritta tem a permissão de "Usar Emojis Externos" em Servidor > Configurações > Cargos > Loritta > Usar Emojis Externos.

**Comment by Pekeanugab** [comment]
Ela tem está permissão.

**Comment by MrPowerGamerBR** [comment]
Era necessário dar "Usar Emojis Externos" para o cargo de `@everyone`, pois o Discord usava as permissões de `@everyone` para interações (Slash Commands, botões, etc)

Hoje em dia ele usa as permissões do cargo do bot mesmo, então se ela tem a permissão, agora deve funcionar corretamente.
