### ISSUE TITLE
Emojis não encontrados

### ISSUE THREAD

**Issue by shinytaiwan** [MrPowerGamerBR/owo#395]
**Qual é o problema?**

Os emojis estão colocados incorretamente no UserInfo da Loritta.

**Como reproduzir o problema?**

1. Re-colocar os emojis, ou trocar-los.
2. ![image](https://user-images.githubusercontent.com/87723311/174157782-34215af1-9f7a-4e17-a543-f065a46d509e.png)

**Comment by MrPowerGamerBR** [comment]
Você precisa dar permissão de "Usar emojis externos" para o cargo de `@everyone`, isso é um bug dos slash commands e será corrigido pelo Discord no futuro.
