### ISSUE TITLE
Voltar as sugestões a como eram antes

### ISSUE THREAD

**Issue by BernardoPC-Dev** [MrPowerGamerBR/owo#412]
Esse novo sistema diminui a interação com "likes" e "deslikes" nas sugestões, dificulta algm ver a sugestão pq precisa entrar no github, as sugestões e bugs no mesmo canal, mt burocracia pra ler e escrever uma sugestão etc

**Comment by 0spura** [comment]
"Devido a grande número de sugestões mal feitas que não explicam a sugestão bem, o grande número de conversas paralelas toda hora que alguém faz uma sugestão polêmica e a falta de conseguir organizar as sugestões para ver as mais votadas, nós decidimos mover as sugestões da Loritta para o GitHub!"
(https://discord.com/channels/297732013006389252/359139508681310212/833342643944554516)
