### ISSUE TITLE
algum bug ocorreu, e me baniram sem motivo

### ISSUE THREAD

**Issue by perlavih** [MrPowerGamerBR/owo#420]
**Qual é o problema?**

me baniram sem motivo, ou por algo que eu não fiz, fui no servidor de suporte da loritta tentar pedir ajuda e só havia o canal de formulário de unban, fiz os formulário como injusto (pois eu achava que tinha sido banida por um motivo, quando na verdade era outro que eu não tinha feito) e agora eu não consigo encontrar nenhum lugar pra poder explicar ou ao menos saber que bug é esse que me baniram por algo que eu não fiz, se eu realmente fiz isso eu quero provas, e além de mim meus dois amigos foram banidos pelo mesmo motivo (compra e venda de produtos de valor monetário por sonhos) e eles não fizeram isso. Ah, e o motivo que vocês me disseram que me levou ao ban foi por causa que eu ofereci robux em troca de sonhos na dm??? eu nunca fiz isso mano, e mesmo se tivesse feito, eu teria oferecido e não cheguei a “vender”? por favor eu espero que entendam, que tentem descobrir que bug é esse que tá levando a banir pessoas sem motivo algum, não sei se vocês erraram o id do usuário sou algo assim. Lembrando que esse foi o único lugar que eu achei para que eu fizesse uma denúncia desse suposto “bug”.

meu id no discord: 668624752696623156
E, obrigado se me entenderem e se forem tentar encontrar uma forma de corrigir esse bug, ou se tentassem me mostrar as provas de que eu realmente fiz aquilo. (podem entrar em contato comigo no pv)

**Comment by MrPowerGamerBR** [comment]
![provay1](https://user-images.githubusercontent.com/9496359/186469321-5434f50e-4fa2-4369-abf6-766a17d71fce.png)
