### ISSUE TITLE
sobre o meu post anterior

### ISSUE THREAD

**Issue by perlavih** [MrPowerGamerBR/owo#421]
![46805F95-3C21-49CD-AD4F-586A1058CB30](https://user-images.githubusercontent.com/106846458/186470297-82b328ec-78f9-4905-9b5a-40f2bb0e8e5e.png)

**Qual é o problema?**

sinto ter que informar vocês mas essa print é fake, eu nunca mandei isso, fiquei até assustada e acho que alguém me hackeou ou algo do tipo, nunca mandei essa mensagem pra ninguém, eu fui correndo trocar minha senha por que isso foi algo inesperado pois nunca dei minha senha a ninguém! tem muita chance disso ser uma edição ou algo assim e além de mim várias pessoas devem estar passando pelo mesmo motivo, sendo banido por algo que elas não fizeram! infelizmente não sei de que modo eu posso realmente provar que não mandei essa mensagem pra ninguém, por favor, se houver algum jeito de provar que eu nunca fiz isso e conseguir ser desbanida, poderiam me dizer? e também, quem foi o usuário que recebeu essa suposta mensagem que diz ser minha?

**Comment by MrPowerGamerBR** [comment]
Aqui não é o lugar para ficar pedindo unban da Loritta, existe o apelo de ban para isso. https://loritta.website/br/extras/faq-loritta/loritta-ban-appeal
